# Generated by Django 5.2.14 on 2026-06-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='describtion',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='describtion',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
